In [2]:

import os
from dotenv import load_dotenv
import getpass

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.llms import OpenAI
from langchain.schema import AIMessage, HumanMessage, SystemMessage
from langchain.memory import ConversationSummaryMemory, ConversationBufferMemory, CombinedMemory
from langchain.chains import ConversationChain
from typing import Any, Dict, Optional, Tuple
from langchain.memory import ChatMessageHistory

from langchain.chains import ConversationChain



os.environ['GOOGLE_API_KEY'] = 'AIzaSyDG8Hh3JEAwWKdXz5j6yjJL2GKOlUy_7es'

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-pro",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2 #,     # other params...
)

embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")

c:\Users\rajes\anaconda3\envs\new_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Below we will create a fancy prompt and have the LLM generate for us sample real estate listings

In [56]:
messages = [
    (
        "system",
        "You are a real estate expert and has lot of knowledge in real estate listings.",
    ),
    ("human", f"""Create 10 sample data records for me in the following format. The format must be a csv, comma seperated adnand double quote seperate for each field.  
     The field and data types are in in the following format: 
     1/Neighborhood: [name], 
     2/ Price: [price], 
     3/ Bedrooms: [number], 
     4/ Bathrooms: [number], 
     5/ House Size: [sqft], 
     6/ House Description: [short description], 
     7/ Neighborhood Description: [short description]. 
     
     See the following sample for better idea 
     Neighborhood: Green Oaks, 
     Price: $800,000, 
     Bedrooms: 3, 
     Bathrooms: 2, 
     House Size: 2,000 sqft,  
     Description: Welcome to this eco-friendly oasis nestled in the heart of Green Oaks. This charming 3-bedroom, 2-bathroom home boasts energy-efficient features such as 
     solar panels and a well-insulated structure. Natural light floods the living spaces, highlighting the beautiful hardwood floors and eco-conscious finishes. 
     The open-concept kitchen and dining area lead to a spacious backyard with a vegetable garden, perfect for the eco-conscious family. 
     Embrace sustainable living without compromising on style in this Green Oaks gem. ,
     Neighborhood Description: Green Oaks is a close-knit, environmentally-conscious 
     community with access to organic grocery stores, community gardens, and bike paths. Take a stroll through the nearby Green Oaks Park or grab a cup of coffee at the cozy Green Bean Cafe. 
     With easy access to public transportation and bike lanes, commuting is a breeze."""),
]
ai_msg = llm.invoke(messages)
ai_msg
print(ai_msg.content)

```csv
"Neighborhood","Price","Bedrooms","Bathrooms","House Size","House Description","Neighborhood Description"
"Green Oaks","$800,000","3","2","2,000 sqft","Welcome to this eco-friendly oasis nestled in the heart of Green Oaks. This charming 3-bedroom, 2-bathroom home boasts energy-efficient features. Natural light floods the living spaces, highlighting the beautiful hardwood floors. The open-concept kitchen and dining area lead to a spacious backyard.","Green Oaks is a close-knit, environmentally-conscious community with access to organic grocery stores and bike paths. Take a stroll through the nearby Green Oaks Park."
"Meadow Creek","$650,000","4","2.5","2,500 sqft","Spacious family home in the desirable Meadow Creek neighborhood. Features a large backyard, updated kitchen, and finished basement.","Meadow Creek offers excellent schools, parks, and a family-friendly atmosphere. Close to shopping and dining."
"City Heights","$1,200,000","2","2","1,800 sqft","Modern condo with stunning city views. Open floor plan, gourmet kitchen, and rooftop terrace.","City Heights is a vibrant urban neighborhood with easy access to restaurants, nightlife, and cultural attractions."
"Sunset Ridge","$725,000","3","2","2,200 sqft","Charming ranch-style home with a large front porch and fenced backyard. Updated bathrooms and kitchen.","Sunset Ridge is a quiet, established neighborhood with mature trees and a peaceful atmosphere."
"Oakwood Estates","$950,000","5","3","3,000 sqft","Executive home in the prestigious Oakwood Estates community. Features a swimming pool, home theater, and gourmet kitchen.","Oakwood Estates offers luxury living with top-rated schools, private security, and exclusive amenities."
"Pine Valley","$550,000","2","1","1,500 sqft","Cozy cottage in the heart of Pine Valley. Perfect for first-time homebuyers or those looking to downsize.","Pine Valley is a charming, walkable neighborhood with local shops, restaurants, and a strong sense of community."
"Riverbend","$775,000","4","3","2,800 sqft","Beautiful home on a large lot in Riverbend. Features a private backyard with a deck and mature trees.","Riverbend offers a tranquil setting with access to nature trails, parks, and the river."
"Hillcrest","$1,100,000","3","2.5","2,400 sqft","Contemporary home with panoramic views in the exclusive Hillcrest neighborhood. High-end finishes and smart home technology.","Hillcrest is a prestigious community with stunning views, private streets, and a luxurious lifestyle."
"Maplewood","$625,000","3","2","1,900 sqft","Updated home in the family-friendly Maplewood neighborhood. Features a new kitchen, hardwood floors, and a fenced backyard.","Maplewood offers excellent schools, parks, and a welcoming community atmosphere."
"Lakeview Terrace","$850,000","4","2.5","2,600 sqft","Stunning lakefront property with breathtaking views. Private dock, large deck, and open floor plan.","Lakeview Terrace offers a serene escape with access to boating, fishing, and other water activities."
```

The above outputs are saved to a .csv file and then later opened in pandas for transformation

In [3]:
import pandas as pd
df = pd.read_csv("realestatelisting.csv")

In [4]:
df.head()

,Neighborhood,Price,Bedrooms,Bathrooms,House Size,House Description,Neighborhood Description
0,Green Oaks,"$800,000",3,2.0,"2,000 sqft",Welcome to this eco-friendly oasis nestled in ...,"Green Oaks is a close-knit, environmentally-co..."
1,Meadowbrook,"$650,000",4,2.5,"2,500 sqft",Spacious family home in Meadowbrook with a lar...,Meadowbrook is a family-friendly neighborhood ...
2,City Heights,"$1,200,000",2,2.0,"1,800 sqft",Modern condo in City Heights with stunning cit...,City Heights offers a vibrant urban lifestyle ...
3,Sunset Ridge,"$725,000",3,2.0,"2,200 sqft",Charming ranch-style home in Sunset Ridge with...,"Sunset Ridge is a quiet, established neighborh..."
4,Oakwood Estates,"$950,000",5,3.0,"3,000 sqft",Executive home in Oakwood Estates with a luxur...,Oakwood Estates is a prestigious community wit...

In [5]:
# !pip install chromadb
# we combine all the descriptive and objective data into a single column.
df
df["Combined Description"] = df['House Description'] +  df['Neighborhood Description']
df

,Neighborhood,Price,Bedrooms,Bathrooms,House Size,House Description,Neighborhood Description,Combined Description
0,Green Oaks,"$800,000",3,2.0,"2,000 sqft",Welcome to this eco-friendly oasis nestled in ...,"Green Oaks is a close-knit, environmentally-co...",Welcome to this eco-friendly oasis nestled in ...
1,Meadowbrook,"$650,000",4,2.5,"2,500 sqft",Spacious family home in Meadowbrook with a lar...,Meadowbrook is a family-friendly neighborhood ...,Spacious family home in Meadowbrook with a lar...
2,City Heights,"$1,200,000",2,2.0,"1,800 sqft",Modern condo in City Heights with stunning cit...,City Heights offers a vibrant urban lifestyle ...,Modern condo in City Heights with stunning cit...
3,Sunset Ridge,"$725,000",3,2.0,"2,200 sqft",Charming ranch-style home in Sunset Ridge with...,"Sunset Ridge is a quiet, established neighborh...",Charming ranch-style home in Sunset Ridge with...
4,Oakwood Estates,"$950,000",5,3.0,"3,000 sqft",Executive home in Oakwood Estates with a luxur...,Oakwood Estates is a prestigious community wit...,Executive home in Oakwood Estates with a luxur...
5,Riverbend,"$580,000",2,1.5,"1,500 sqft",Cozy cottage in Riverbend with river views. Up...,Riverbend is a charming neighborhood with a sm...,Cozy cottage in Riverbend with river views. Up...
6,Pinewood,"$700,000",4,2.0,"2,300 sqft",Updated split-level home in Pinewood with a la...,Pinewood is a family-oriented neighborhood wit...,Updated split-level home in Pinewood with a la...
7,Hillcrest,"$1,100,000",3,2.5,"2,800 sqft",Contemporary home in Hillcrest with panoramic ...,Hillcrest offers breathtaking views and a luxu...,Contemporary home in Hillcrest with panoramic ...
8,Harbor View,"$875,000",4,3.0,"2,600 sqft",Beautiful home in Harbor View with water views...,Harbor View is a waterfront community with acc...,Beautiful home in Harbor View with water views...
9,Willow Creek,"$620,000",3,2.0,"1,900 sqft",Charming home in Willow Creek with a large bac...,Willow Creek is a peaceful neighborhood with a...,Charming home in Willow Creek with a large bac...

In [ ]:
For semantic search to be possible, we will now initialize the chromadb store and
save contents from the dataframe into the store.

In [11]:
from chromadb.config import Settings
import chromadb
collection_name = "real_estate"

# Initialize the ChromaDB client
client = chromadb.Client(Settings())

# List all collection names
existing_collections = client.list_collections()
print("Existing Collections:", existing_collections)
if collection_name in existing_collections:
    print(f"The collection '{collection_name}' exists.")
    client.delete_collection(collection_name)
    collection = client.create_collection("real_estate")
    print(f"The collection '{collection_name}' has been created.")
else:
    print(f"The collection '{collection_name}' does not exist.")
    collection = client.create_collection("real_estate")
    print(f"The collection '{collection_name}' has been created.")

Existing Collections: []
The collection 'real_estate' does not exist.
The collection 'real_estate' has been created.

In [12]:
# the google embedding and save all records from pandas dataframe in a loop into the chromadb store.

embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
# Insert data into ChromaDB
for index, row in df.iterrows():
    # Create a unique ID for each listing
    listing_id = f"listing_{index}"
    
    # Generate embedding for the combined description
    embedding = embeddings.embed_query(row["Combined Description"])
    
    # Add the listing to ChromaDB
    collection.add(
        ids=[listing_id],
        embeddings=[embedding],
        metadatas=[{
            "Neighborhood": row["Neighborhood"],
            "Price": row["Price"],
            "Bedrooms": row["Bedrooms"],
            "Bathrooms": row["Bathrooms"],
            "House Size": row["House Size"],
            "House Description": row["House Description"],
            "Neighborhood Description": row["Neighborhood Description"]
        }]
    )

print("Data successfully inserted into ChromaDB!")

Data successfully inserted into ChromaDB!

In [13]:
# Step 6: Query Example 1 (Optional) to pull data from the chromadb store
# Example of semantic search in ChromaDB
# query = "ranch style"
query = "eco-friendly community with good schools"
query_embedding = embeddings.embed_query(query)

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=2
)

# print("\nTop Matches:")
# for result in results["metadatas"]:
#     print(f"Neighborhood: {result['Neighborhood']}")
#     print(f"Price: {result['Price']}")
#     print(f"House Description: {result['House Description']}\n")

for result_list in results["metadatas"]:
    for result in result_list:
        print(f"Neighborhood: {result['Neighborhood']}")
        print(f"Price: {result['Price']}")
        print(f"Bedrooms: {result['Bedrooms']}")
        print(f"Bathrooms: {result['Bathrooms']}")
        print(f"House Size: {result['House Size']}")
        print(f"Neighborhood Description: {result['Neighborhood Description']}")
        print(f"House Description: {result['House Description']}\n")

Neighborhood: Green Oaks
Price: $800,000
Bedrooms: 3
Bathrooms: 2.0
House Size: 2,000 sqft
Neighborhood Description: Green Oaks is a close-knit, environmentally-conscious community with access to organic grocery stores and community gardens.
House Description: Welcome to this eco-friendly oasis nestled in the heart of Green Oaks. This charming 3-bedroom, 2-bathroom home boasts energy-efficient features.

Neighborhood: Meadowbrook
Price: $650,000
Bedrooms: 4
Bathrooms: 2.5
House Size: 2,500 sqft
Neighborhood Description: Meadowbrook is a family-friendly neighborhood with excellent schools, parks, and a community center.
House Description: Spacious family home in Meadowbrook with a large backyard, perfect for entertaining. Features a modern kitchen and updated bathrooms.

In [14]:
# Step 6: Query Example 2 (Optional) to pull data from the chromadb store
query = "ranch style neighborhood"
query_embedding = embeddings.embed_query(query)

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=2
)

# print("\nTop Matches:")
# for result in results["metadatas"]:
#     print(f"Neighborhood: {result['Neighborhood']}")
#     print(f"Price: {result['Price']}")
#     print(f"House Description: {result['House Description']}\n")

for result_list in results["metadatas"]:
    for result in result_list:
        print(f"Neighborhood: {result['Neighborhood']}")
        print(f"Price: {result['Price']}")
        print(f"Bedrooms: {result['Bedrooms']}")
        print(f"Bathrooms: {result['Bathrooms']}")
        print(f"House Size: {result['House Size']}")
        print(f"Neighborhood Description: {result['Neighborhood Description']}")
        print(f"House Description: {result['House Description']}\n")

Neighborhood: Sunset Ridge
Price: $725,000
Bedrooms: 3
Bathrooms: 2.0
House Size: 2,200 sqft
Neighborhood Description: Sunset Ridge is a quiet, established neighborhood with tree-lined streets and a peaceful atmosphere.
House Description: Charming ranch-style home in Sunset Ridge with a large front porch and mature landscaping. Updated kitchen and spacious bedrooms.

Neighborhood: Oakwood Estates
Price: $950,000
Bedrooms: 5
Bathrooms: 3.0
House Size: 3,000 sqft
Neighborhood Description: Oakwood Estates is a prestigious community with large homes, manicured lawns, and a country club.
House Description: Executive home in Oakwood Estates with a luxurious master suite and a finished basement.  Large backyard with a pool.

In [15]:
# Now we will create the static questions and answers for the real estate expert chatbot.
personal_questions = [   
                "How big do you want your house to be?" 
                "What are 3 most important things for you in choosing this property?", 
                "Which amenities would you like?", 
                "Which transportation options are important to you?",
                "How urban do you want your neighborhood to be?",   
            ]
personal_answers = [
    "A comfortable three-bedroom house with a spacious kitchen and a cozy living room.",
    "A quiet neighborhood, good local schools, and convenient shopping options.",
    "A backyard for gardening, a two-car garage, and a modern, energy-efficient heating system.",
    "Easy access to a reliable bus line, proximity to a major highway, and bike-friendly roads.",
    "A balance between suburban tranquility and access to urban amenities like restaurants and theaters."
]

In [ ]:

# # Use Conversation Memory for Real Estate Recommendation

# #
# # Initialize chat history
# history = ChatMessageHistory()
# history.add_user_message(f"""You are a real estate AI agent that will recommend user the best house that matches their criteria. To get to the best match, ask user {len(personal_questions)} questions""")

# for i in range(len(personal_questions)):
#     history.add_ai_message(personal_questions[i])
#     history.add_user_message(personal_answers[i])

# history.add_ai_message(f"""Now based on the information come up with a real estate listing summary for the human""")

# # Setup summary memory
# summary_memory = ConversationSummaryMemory(
#     llm=ChatOpenAI(temperature=0.7, openai_api_key=api_key),
#     memory_key="recommendation_summary",
#     input_key="input",
#     buffer=f"The human answered {len(personal_questions)} personal questions. Use them to recommend the best real estate listing."
# )

# print(summary_memory)


# class MementoBufferMemory(ConversationBufferMemory):
#     def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
#         input_str, output_str = self._get_input_output(inputs, outputs)
#         self.chat_memory.add_ai_message(output_str)
    
# conversational_memory = MementoBufferMemory(
#     chat_memory=history,
#     memory_key="questions_and_answers", 
#     input_key="input"
# )

# memory = CombinedMemory(memories=[conversational_memory, summary_memory])

# # ## based on the combined history, we need to know use the chroma databse and pull the best real estate listing
# # # Example interaction

In [27]:

# Pull the best real estate matches from ChromaDB and add to chat history
recommendation_query = "".join(personal_answers)  # Combine user answers into a single query
recommendation_query_embedding = embeddings.embed_query(recommendation_query)

best_matches = collection.query(
    query_embeddings=[recommendation_query_embedding],
    n_results=5
    # ,include_distances=True
)

# Sort results by distance and retrieve the results in desc order of the COSINE distance.

sorted_matches = []
for distance_list, metadata_list in zip(best_matches["distances"], best_matches["metadatas"]):
    for distance, metadata in zip(distance_list, metadata_list):
        sorted_matches.append((distance, metadata))

sorted_matches.sort(key=lambda x: x[0], reverse=True)

# Ensure all sorted results are printed
# for distance, metadata in sorted_matches:
#     match_message = (
#         f"Distance: {distance:.4f}, Neighborhood: {metadata['Neighborhood']}, Price: {metadata['Price']}, Bedrooms: {metadata['Bedrooms']}, "
#         f"Bathrooms: {metadata['Bathrooms']}, House Size: {metadata['House Size']}, "
#         f"Neighborhood Description: {metadata['Neighborhood Description']}, "
#         f"House Description: {metadata['House Description']}"
#     )
#     history.add_ai_message(match_message)

# Print the sorted results with distances
print("\nSorted Results with Distances:")
for distance, metadata in sorted_matches:
    print(f"Distance: {distance:.4f}")
    print(f"Neighborhood: {metadata['Neighborhood']}")
    print(f"Price: {metadata['Price']}")
    print(f"Bedrooms: {metadata['Bedrooms']}")
    print(f"Bathrooms: {metadata['Bathrooms']}")
    print(f"House Size: {metadata['House Size']}")
    print(f"Neighborhood Description: {metadata['Neighborhood Description']}")
    print(f"House Description: {metadata['House Description']}\n")

# # Print the full conversation history
# print("\nFull Conversation History:")
# for message in history.messages:
#     print(f"{message['role']}: {message['content']}")

Sorted Results with Distances:
Distance: 0.5691
Neighborhood: Green Oaks
Price: $800,000
Bedrooms: 3
Bathrooms: 2.0
House Size: 2,000 sqft
Neighborhood Description: Green Oaks is a close-knit, environmentally-conscious community with access to organic grocery stores and community gardens.
House Description: Welcome to this eco-friendly oasis nestled in the heart of Green Oaks. This charming 3-bedroom, 2-bathroom home boasts energy-efficient features.

Distance: 0.5633
Neighborhood: Pinewood
Price: $700,000
Bedrooms: 4
Bathrooms: 2.0
House Size: 2,300 sqft
Neighborhood Description: Pinewood is a family-oriented neighborhood with good schools, parks, and a community pool.
House Description: Updated split-level home in Pinewood with a large family room and a fenced backyard. Close to schools and parks.

Distance: 0.5607
Neighborhood: Sunset Ridge
Price: $725,000
Bedrooms: 3
Bathrooms: 2.0
House Size: 2,200 sqft
Neighborhood Description: Sunset Ridge is a quiet, established neighborhood with tree-lined streets and a peaceful atmosphere.
House Description: Charming ranch-style home in Sunset Ridge with a large front porch and mature landscaping. Updated kitchen and spacious bedrooms.

Distance: 0.5525
Neighborhood: Willow Creek
Price: $620,000
Bedrooms: 3
Bathrooms: 2.0
House Size: 1,900 sqft
Neighborhood Description: Willow Creek is a peaceful neighborhood with a strong sense of community, close to nature trails and parks.
House Description: Charming home in Willow Creek with a large backyard and a screened porch. Close to parks and walking trails.

Distance: 0.5017
Neighborhood: Meadowbrook
Price: $650,000
Bedrooms: 4
Bathrooms: 2.5
House Size: 2,500 sqft
Neighborhood Description: Meadowbrook is a family-friendly neighborhood with excellent schools, parks, and a community center.
House Description: Spacious family home in Meadowbrook with a large backyard, perfect for entertaining. Features a modern kitchen and updated bathrooms.

In [38]:
for distance, metadata in sorted_matches:
    combined_description = "  House Description: " + metadata['House Description'] + " Neighborhood Description: " + metadata['Neighborhood Description']
    combined_description = combined_description + "  Neighborhood: " + metadata['Neighborhood']
    combined_description = combined_description + "  Price: " + metadata['Price']
    combined_description = combined_description + "  Bedrooms: " + str(metadata['Bedrooms'])
    combined_description = combined_description + "  Bathrooms: " + str( metadata['Bathrooms'])
    combined_description = combined_description + "  House Size: " + metadata['House Size']
    print(combined_description)
    
    messages = [
    (
        "system",
        """You are an advanced AI specializing in real estate recommendations. 
    Based on the following detailed description of a property, provide a tailored summary that highlights 
    the key features and makes it appealing for a potential buyer:""",
    ),
    ("human", {combined_description} )
    ]
 
    llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-pro",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2 #,     # other params...
    )
    llm_aug_msg = llm.invoke(messages)
    
    print(f"LLM Augmented Description: {llm_aug_msg.content}")
    print(f"combined_description: {combined_description}")
    # print(f"Distance: {distance:.4f}")
    # print(f"Neighborhood: {metadata['Neighborhood']}")
    # print(f"Price: {metadata['Price']}")
    # print(f"Bedrooms: {metadata['Bedrooms']}")
    # print(f"Bathrooms: {metadata['Bathrooms']}")
    # print(f"House Size: {metadata['House Size']}")
    # print(f"Neighborhood Description: {metadata['Neighborhood Description']}")
    # print(f"House Description: {metadata['House Description']}\n")

  House Description: Welcome to this eco-friendly oasis nestled in the heart of Green Oaks. This charming 3-bedroom, 2-bathroom home boasts energy-efficient features. Neighborhood Description: Green Oaks is a close-knit, environmentally-conscious community with access to organic grocery stores and community gardens.  Neighborhood: Green Oaks  Price: $800,000  Bedrooms: 3  Bathrooms: 2.0  House Size: 2,000 sqft
LLM Augmented Description: Live green in the heart of Green Oaks! This charming 3-bedroom, 2-bath, 2,000 sq ft home offers eco-conscious living at its finest.  Enjoy a tranquil setting within this close-knit community, surrounded by like-minded neighbors and with easy access to organic grocers and community gardens.  Priced at $800,000, this energy-efficient oasis provides both comfort and sustainability.  Contact us today to experience the Green Oaks lifestyle!

combined_description:   House Description: Welcome to this eco-friendly oasis nestled in the heart of Green Oaks. This charming 3-bedroom, 2-bathroom home boasts energy-efficient features. Neighborhood Description: Green Oaks is a close-knit, environmentally-conscious community with access to organic grocery stores and community gardens.  Neighborhood: Green Oaks  Price: $800,000  Bedrooms: 3  Bathrooms: 2.0  House Size: 2,000 sqft
  House Description: Updated split-level home in Pinewood with a large family room and a fenced backyard. Close to schools and parks. Neighborhood Description: Pinewood is a family-oriented neighborhood with good schools, parks, and a community pool.  Neighborhood: Pinewood  Price: $700,000  Bedrooms: 4  Bathrooms: 2.0  House Size: 2,300 sqft
LLM Augmented Description: Welcome home to this beautifully updated split-level in the desirable Pinewood neighborhood!  This spacious 4-bedroom, 2-bathroom, 2,300 sqft home offers the perfect blend of modern living and family-friendly charm.  Enjoy gatherings in the generously sized family room, ideal for movie nights or game days.  The fenced backyard provides a private oasis for kids and pets to play freely.  Located just a stone's throw from top-rated schools, parks, and the community pool, this home offers an unparalleled lifestyle.  Don't miss out on this fantastic opportunity in the heart of Pinewood, priced at $700,000.

combined_description:   House Description: Updated split-level home in Pinewood with a large family room and a fenced backyard. Close to schools and parks. Neighborhood Description: Pinewood is a family-oriented neighborhood with good schools, parks, and a community pool.  Neighborhood: Pinewood  Price: $700,000  Bedrooms: 4  Bathrooms: 2.0  House Size: 2,300 sqft
  House Description: Charming ranch-style home in Sunset Ridge with a large front porch and mature landscaping. Updated kitchen and spacious bedrooms. Neighborhood Description: Sunset Ridge is a quiet, established neighborhood with tree-lined streets and a peaceful atmosphere.  Neighborhood: Sunset Ridge  Price: $725,000  Bedrooms: 3  Bathrooms: 2.0  House Size: 2,200 sqft
LLM Augmented Description: Picture yourself relaxing on the spacious front porch of this charming ranch-style home in the desirable Sunset Ridge neighborhood.  Offered at $725,000, this 2,200 sq ft home boasts 3 bedrooms and 2 bathrooms, perfect for comfortable living.  The updated kitchen is ready for your culinary creations, and generously sized bedrooms provide ample space for rest and relaxation.  Mature landscaping enhances the curb appeal and welcomes you to this peaceful retreat. Sunset Ridge offers tree-lined streets and a tranquil atmosphere, making it an ideal place to call home.

combined_description:   House Description: Charming ranch-style home in Sunset Ridge with a large front porch and mature landscaping. Updated kitchen and spacious bedrooms. Neighborhood Description: Sunset Ridge is a quiet, established neighborhood with tree-lined streets and a peaceful atmosphere.  Neighborhood: Sunset Ridge  Price: $725,000  Bedrooms: 3  Bathrooms: 2.0  House Size: 2,200 sqft
  House Description: Charming home in Willow Creek with a large backyard and a screened porch. Close to parks and walking trails. Neighborhood Description: Willow Creek is a peaceful neighborhood with a strong sense of community, close to nature trails and parks.  Neighborhood: Willow Creek  Price: $620,000  Bedrooms: 3  Bathrooms: 2.0  House Size: 1,900 sqft
LLM Augmented Description: Escape to tranquility in this charming 3-bedroom, 2-bath, 1900 sq ft home nestled in the desirable Willow Creek neighborhood.  Enjoy peaceful evenings on the screened porch overlooking a spacious backyard, perfect for relaxation and entertaining.  Nature lovers will appreciate the proximity to parks and walking trails, offering endless opportunities for outdoor recreation.  Become part of the strong Willow Creek community and experience the serenity of this sought-after location. Offered at $620,000.

combined_description:   House Description: Charming home in Willow Creek with a large backyard and a screened porch. Close to parks and walking trails. Neighborhood Description: Willow Creek is a peaceful neighborhood with a strong sense of community, close to nature trails and parks.  Neighborhood: Willow Creek  Price: $620,000  Bedrooms: 3  Bathrooms: 2.0  House Size: 1,900 sqft
  House Description: Spacious family home in Meadowbrook with a large backyard, perfect for entertaining. Features a modern kitchen and updated bathrooms. Neighborhood Description: Meadowbrook is a family-friendly neighborhood with excellent schools, parks, and a community center.  Neighborhood: Meadowbrook  Price: $650,000  Bedrooms: 4  Bathrooms: 2.5  House Size: 2,500 sqft
LLM Augmented Description: Looking for the perfect family home in a top-rated neighborhood? Look no further! This spacious 4-bedroom, 2.5-bathroom home in desirable Meadowbrook offers 2,500 sq ft of comfortable living space, including a modern, updated kitchen perfect for family meals and entertaining.  The expansive backyard is an entertainer's dream, offering plenty of room for kids to play, summer barbecues, and creating lasting memories.  Meadowbrook itself boasts excellent schools, beautiful parks, and a vibrant community center, providing a welcoming atmosphere for families of all ages.  Offered at $650,000, this home represents an incredible opportunity to enjoy the Meadowbrook lifestyle. Don't miss out – schedule your showing today!

combined_description:   House Description: Spacious family home in Meadowbrook with a large backyard, perfect for entertaining. Features a modern kitchen and updated bathrooms. Neighborhood Description: Meadowbrook is a family-friendly neighborhood with excellent schools, parks, and a community center.  Neighborhood: Meadowbrook  Price: $650,000  Bedrooms: 4  Bathrooms: 2.5  House Size: 2,500 sqft

In [20]:
import openai
os.environ["OPENAI_API_KEY"] = "voc-19870251031266773654982673492659e28d3.25747737"
os.environ["OPENAI_API_BASE"] = "https://openai.vocareum.com/v1"
openai.api_base = "https://openai.vocareum.com/v1"
# Define your OpenAI API key 
api_key = "voc-19870251031266773654982673492659e28d3.25747737"
openai.api_key = api_key

model_name = "gpt-3.5-turbo"
temperature = 0.0
llm = OpenAI(model_name=model_name, temperature=temperature, max_tokens = 1000)

c:\Users\rajes\anaconda3\envs\new_env\lib\site-packages\langchain_community\llms\openai.py:254: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain_community.chat_models import ChatOpenAI`
  warnings.warn(
c:\Users\rajes\anaconda3\envs\new_env\lib\site-packages\langchain_community\llms\openai.py:1076: UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain_community.chat_models import ChatOpenAI`
  warnings.warn(